# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc7962cddff11d73d9d8e0e028f78170773506a97b311b4190f2f1356d30ac7e1663207da3c3426d2ff8a214b2fbe0a95a8c97fd284aa3cf8ec840d86f694ad3

test:
  secret_key_base: 19890397332905c73374664764acac677f354f841fbf1a2c70ab1681bbf21ba1e32baef56c92d8efbbd54b7f22cb9c8e7c45b58ea3150476d502ba37fb80b1b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
